# Generated by Django 5.2 on 2025-06-30 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_review_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='file',
            field=models.FileField(default=4, upload_to='jobs/files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
            preserve_default=False,
        ),
    ]
