# Generated by Django 5.2 on 2025-06-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobimage_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobimage',
            name='file',
        ),
    ]
