# Generated by Django 5.2 on 2025-06-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_remove_jobimage_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobimage',
            old_name='product',
            new_name='job',
        ),
    ]
