# Generated by Django 5.2 on 2025-06-30 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_rename_product_jobimage_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='duration_days',
            field=models.PositiveIntegerField(default=1, help_text='Number of days required to complete the job', validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
