# Generated by Django 5.2 on 2025-06-30 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_created_by_job_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='job.jobprice'),
        ),
    ]
