# Generated by Django 5.2 on 2025-07-02 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_jobprice_alter_job_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['name', 'description', 'category'], name='job_job_name_bb1d81_idx'),
        ),
    ]
