# Generated by Django 5.2 on 2025-07-02 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_job_job_job_name_bb1d81_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='job.job'),
        ),
    ]
