# Generated by Django 5.2 on 2025-07-02 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_review_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['job', 'created_at'], name='job_review_job_id_df24fd_idx'),
        ),
    ]
