# Generated by Django 5.2 on 2025-05-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_rename_testreview_review'),
        ('order', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'job')},
        ),
    ]
