# Generated by Django 5.2 on 2025-06-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Paid', 'Not Paid'), ('Accepted', 'Accepted'), ('In Progress', 'In Progress'), ('Submitted', 'Submitted'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Not Paid', max_length=20),
        ),
    ]
