# Generated by Django 5.2 on 2025-06-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
