# Generated by Django 5.2 on 2025-06-30 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_deadline_alter_order_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='order_deliveries')),
                ('description', models.TextField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivered_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='order.order')),
            ],
        ),
    ]
