# Generated by Django 5.2 on 2025-07-03 00:47

import django.core.validators
import job.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_review_job_review_job_id_df24fd_idx'),
        ('order', '0009_orderdelivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdelivery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order_deliveries', validators=[job.validators.delivery_validate_file_size]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'created_at'], name='order_cart_user_id_236745_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'job'], name='order_carti_cart_id_983a33_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', 'created_at'], name='order_order_user_id_38175f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderdelivery',
            index=models.Index(fields=['order', 'delivered_by', 'delivered_at'], name='order_order_order_i_bb2216_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'job', 'freelancer'], name='order_order_order_i_e3f3d7_idx'),
        ),
    ]
